# Generated by Django 5.1.15 on 2026-07-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
    ]
