# Generated by Django 5.1.15 on 2026-08-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
