# Generated by Django 5.1.15 on 2026-07-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
