# Generated by Django 5.0.4 on 2026-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_shop_suspended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='emi_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
