# Generated by Django 5.1.15 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_alter_shop_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='manufacturing_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable Manufacturing & Batch Production section'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_type',
            field=models.CharField(choices=[('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Cosmetics'), ('jewelry', 'Jewelry & Accessories'), ('home_decor', 'Home Decor & Furniture'), ('food', 'Groceries & Organic Food'), ('footwear', 'Footwear & Shoes'), ('handcrafts', 'Handcrafts & Boutique'), ('electronics', 'Electronics & Gadgets'), ('computer', 'Computer & IT'), ('mobile', 'Mobile & Accessories'), ('general', 'General Retail'), ('camical', 'Camical'), ('supershop', 'Supershop'), ('cosmetics', 'Chemical & Lab Supplies'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
