# Generated by Django 5.1.15 on 2026-07-21 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('purchasing', '0002_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
