# Generated by Django 5.1.15 on 2026-07-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_supplier_product_warranty_months'),
        ('sales', '0003_sale_customer_address_sale_customer_name_and_more'),
        ('tenants', '0003_shop_suspended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold')], default='in_stock', max_length=10)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='sales.sale')),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'barcode'], name='catalog_pro_shop_id_fe14b8_idx'), models.Index(fields=['shop', 'status'], name='catalog_pro_shop_id_2f656f_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'barcode'), name='uniq_unit_barcode_per_shop')],
            },
        ),
    ]
