# Generated by Django 5.1.15 on 2026-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productunit'),
        ('purchasing', '0003_supplier_company_name'),
        ('tenants', '0003_shop_suspended_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('shop', 'barcode'), name='uniq_barcode_per_shop_when_set'),
        ),
    ]
