# Generated by Django 5.1.15 on 2026-07-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_uniq_barcode_per_shop_when_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold'), ('returned', 'Returned')], default='in_stock', max_length=10),
        ),
    ]
