# Generated by Django 5.1.15 on 2026-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productunit_cost_price_productunit_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
