# Generated by Django 5.1.15 on 2026-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold'), ('returned', 'Returned'), ('defective', 'Defective'), ('returned_supplier', 'Returned to supplier'), ('testing_pending', 'Testing Pending')], default='in_stock', max_length=20),
        ),
    ]
