# Generated by Django 5.1.15 on 2026-08-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacement_guarantee_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productunit',
            name='replacement_guarantee_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
