# Generated by Django 5.1.15 on 2026-09-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_unit_allow_decimal_unit_measure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_multiplier',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_products', to='catalog.unit'),
        ),
    ]
