# Generated by Django 5.1.15 on 2026-09-03
# Adds full_pack_cost and full_pack_sell to Product model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_purchase_multiplier_product_purchase_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_pack_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='full_pack_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]