# Generated by Django 5.1.15 on 2026-09-08 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_full_pack_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for chemicals/liquids', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gender_target',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Batch or Lot number', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(blank=True, help_text='Manufacturing date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all', 'All Season'), ('monsoon', 'Monsoon')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variants',
            field=models.JSONField(blank=True, default=list, help_text='[{"size":"M","color":"Red","stock":10},...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_pack_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_pack_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
