# Generated by Django 5.1.15 on 2026-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_expiry_date_product_fabric_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='collection_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_target',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all', 'All Season'), ('monsoon', 'Monsoon')], default='', max_length=60),
        ),
    ]
