# Generated by Django 5.1.15 on 2026-07-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription_auto_renew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('payment_due', 'Payment due'), ('subscription', 'Subscription'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_channels', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_read', 'created_at'], name='notificatio_shop_id_d660c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_stock_enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily digest')], default='daily', max_length=10)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop',), name='uniq_alert_config_per_shop')],
            },
        ),
    ]
