# Generated by Django 5.1.15 on 2026-07-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('use_platform_number', models.BooleanField(default=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=60)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop',), name='uniq_whatsapp_config_per_shop')],
            },
        ),
    ]
