# Generated by Django 5.1.15 on 2026-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_shopwhatsappconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopalertconfig',
            name='mode',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily digest')], default='realtime', max_length=10),
        ),
    ]
