# Generated by Django 5.1.15 on 2026-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_shopalertconfig_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopalertconfig',
            name='daily_report_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopalertconfig',
            name='monthly_report_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopalertconfig',
            name='report_recipient_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopalertconfig',
            name='weekly_report_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
