# Generated by Django 5.1.15 on 2026-07-26 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchasepayment'),
        ('tenants', '0003_shop_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_amount_positive'),
        ),
    ]
