# Generated by Django 5.1.15 on 2026-08-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchaseorder_supplier_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='barcodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier'),
        ),
    ]
