# Generated by Django 5.1.15 on 2026-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_purchaseorderitem_barcodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank transfer'), ('settlement', 'Settlement / Adjustment')], default='cash', max_length=20),
        ),
    ]
