# Generated by Django 5.1.15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_purchaseorder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank transfer'), ('settlement', 'Settlement / Adjustment')], default='cash', max_length=20),
        ),
    ]
