# Generated by Django 5.1.15 on 2026-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
