# Generated by Django 5.1.15 on 2026-07-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceticket_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='device_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('console', 'Gaming console'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='issue_type',
            field=models.CharField(choices=[('screen', 'Cracked / faulty screen'), ('battery', 'Battery / charging'), ('software', 'OS / software'), ('liquid', 'Liquid damage'), ('power', 'Boot / power'), ('virus', 'Virus / malware'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
