# Generated by Django 5.1.15 on 2026-07-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceticket_device_type_serviceticket_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='service.warranty'),
        ),
    ]
