# Generated by Django 5.1.15 on 2026-07-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productunit_status'),
        ('service', '0004_serviceticket_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='product_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='catalog.productunit'),
        ),
    ]
