# Generated by Django 5.1.15 on 2026-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_warranty_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
