# Generated by Django 5.1.15 on 2026-08-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_warrantyclaim_expected_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='serviceticketpart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
