# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_serviceticket_paid_serviceticketpart_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
