# Generated by Django 5.1.15 on 2026-09-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_serviceticket_track_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='imei_serial',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
