# Generated by Django 5.1.15 on 2026-09-19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("crm", "0001_initial"),
        ("service", "0011_serviceticket_imei_serial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_number", models.CharField(db_index=True, max_length=40)),
                ("track_token", models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ("customer_name", models.CharField(max_length=150)),
                ("customer_phone", models.CharField(max_length=30)),
                ("service_type", models.CharField(max_length=100)),
                ("reference_no", models.CharField(blank=True, max_length=120)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("govt_fee", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("service_charge", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("material_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("other_charge", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_bill", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("advance_paid", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("due_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("ready", "Ready for Delivery"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=20)),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_jobs", to="tenants.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_service_jobs", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_jobs", to="crm.customer")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.shop")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceJobMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("from_stock", models.BooleanField(default=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="service.servicejob")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="job_materials", to="catalog.product")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.shop")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceJobStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="job_status_changes", to=settings.AUTH_USER_MODEL)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="service.servicejob")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.shop")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="servicejob",
            constraint=models.UniqueConstraint(fields=("shop", "job_number"), name="uniq_job_number_per_shop"),
        ),
    ]
