# Generated by Django 5.1.15 on 2026-09-19 18:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_servicejob_servicejobmaterial_servicejobstatushistory'),
        ('tenants', '0026_alter_shop_mobile_repair_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='artwork_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='design_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='design_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='finishing_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='meter_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='meter_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='shop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop'),
        ),
        migrations.AlterField(
            model_name='servicejobmaterial',
            name='shop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop'),
        ),
        migrations.AlterField(
            model_name='servicejobstatushistory',
            name='shop',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop'),
        ),
    ]
