# Generated by Django 5.1.15 on 2026-07-26 23:00

from django.conf import settings
from django.db import migrations, models


def _clamp_negative_expenses(apps, schema_editor):
    """Legacy/erroneous negative expense amounts would violate the new CHECK.
    Clamp them to 0 so the constraint applies cleanly (real data has none)."""
    Expense = apps.get_model('accounting', 'Expense')
    Expense.objects.filter(amount__lt=0).update(amount=0)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_recurringexpense'),
        ('tenants', '0003_shop_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_clamp_negative_expenses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expense_amount_non_negative'),
        ),
    ]
