# Generated by Django 5.1.15 on 2026-08-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_dailysettlement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailysettlement',
            new_name='accounting__shop_id_8af6ae_idx',
            old_name='accounting_dail_idx',
        ),
    ]
