# Generated by Django 5.1.15 on 2026-08-26 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_dailysettlement_investment_fields'),
        ('tenants', '0017_shop_offline_sale_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='type',
            field=models.CharField(choices=[('capital', 'Owner / Partner Capital'), ('drawing', 'Owner Withdrawal / Drawings'), ('loan', 'Loan / Borrowing'), ('equity', 'Equity / Share'), ('other', 'Other Investment')], default='capital', max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('to_account', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], default='bkash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('transferred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
            ],
            options={
                'ordering': ['-transferred_on', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'transferred_on'], name='accounting__shop_id_02f9d9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_amount_positive')],
            },
        ),
    ]
