# Generated by Django 5.1.15 on 2026-07-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('rate_tier', models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise')], default='standard', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
