# Generated by Django 5.1.15 on 2026-07-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('segment', models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('vip', 'VIP'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('due_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.shop')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['shop', 'phone'], name='crm_custome_shop_id_ab4bbe_idx')],
            },
        ),
    ]
