# Generated by Django 5.1.15 on 2026-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
