# Generated by Django 5.1.15 on 2026-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_whatsapp_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
