# Generated by Django 5.1.15 on 2026-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('purchase_in', 'Purchase received'), ('sale_out', 'Sale'), ('sale_return_in', 'Sale return'), ('purchase_return_out', 'Purchase return'), ('adjust_in', 'Adjustment (in)'), ('adjust_out', 'Adjustment (out)'), ('damage_out', 'Damaged / lost / expired'), ('transfer_in', 'Branch transfer in'), ('transfer_out', 'Branch transfer out'), ('production_in', 'Production yield (in)'), ('production_out', 'Production raw material (out)')], max_length=30),
        ),
    ]
