# Generated by Django 5.1.15 on 2026-07-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='exchange_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanged_from', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank transfer'), ('store_credit', 'Store credit'), ('exchange', 'Exchange (no cash)')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('due', 'Due'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('partially_returned', 'Partially returned')], default='due', max_length=20),
        ),
    ]
