# Generated by Django 5.1.15 on 2026-07-26 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_discount_percent'),
        ('sales', '0003_sale_customer_address_sale_customer_name_and_more'),
        ('tenants', '0003_shop_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('shop', 'idempotency_key'), name='uniq_sale_idempotency_key'),
        ),
    ]
