# Generated by Django 5.1.15 on 2026-07-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_idempotency_key_sale_uniq_sale_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='restocked',
            field=models.BooleanField(default=True),
        ),
    ]
