# Generated by Django 5.1.15 on 2026-07-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salereturn_restocked'),
        ('tenants', '0003_shop_suspended_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
