# Generated by Django 5.1.15 on 2026-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_payment_payment_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
