# Generated by Django 5.1.15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank transfer'), ('settlement', 'Settlement / Adjustment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('due', 'Due'), ('quotation', 'Quotation'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('partially_returned', 'Partially returned')], default='due', max_length=20),
        ),
    ]
