# Generated by Django 5.1.15 on 2026-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_payment_method_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='alteration_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='alteration_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
