# Generated by Django 5.1.15 on 2026-07-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='Full YouTube link (watch, youtu.be, or embed).')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=1, help_text='Play order — lower numbers show first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sequence'], name='platform_ad_is_acti_5f9a98_idx')],
            },
        ),
    ]
