# Generated by Django 5.1.15 on 2026-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_platformconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformconfig',
            name='drive_credentials_json',
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='drive_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='drive_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='drive_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
