# Generated by Django 5.1.15 on 2026-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_remove_platformconfig_drive_credentials_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='drive_backup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='drive_backup_interval_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
    ]
