# Generated by Django 5.1.15 on 2026-08-09 11:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_platformconfig_drive_backup_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='Markdown or HTML content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for the blog listing')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional absolute URL for a cover image')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['is_published', 'published_at'], name='platform_ad_is_publ_5cece9_idx'),
                ],
            },
        ),
    ]
