# Generated by Django 5.1.15 on 2026-08-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0007_platformconfig_smtp_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='platform_ad_is_publ_0ff934_idx',
            old_name='platform_ad_is_publ_5cece9_idx',
        ),
    ]
