# Generated by Django 5.0 on 2026-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0018_tutorialvideo_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('mac', 'macOS')], max_length=20)),
                ('version', models.CharField(help_text='e.g., v1.2.0', max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload the executable or APK', upload_to='software/')),
                ('is_active', models.BooleanField(default=True, help_text="If false, this version won't be visible to users")),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_active', '-created_at'], name='platform_ad_platfor_ab1234_idx')],
            },
        ),
    ]
