# Generated by Django 5.1.15 on 2026-07-26 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_shop_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('products', 'Products'), ('supplier_dues', 'Supplier dues'), ('customer_dues', 'Customer dues')], max_length=20)),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('detected_columns', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('mapping', 'Mapping'), ('validating', 'Validating'), ('preview_ready', 'Preview ready'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('error_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='tenants.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('products', 'Products'), ('supplier_dues', 'Supplier dues'), ('customer_dues', 'Customer dues')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_mappings', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_mappings', to='tenants.shop')),
            ],
            options={
                'ordering': ['import_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('cleaned_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('error', 'Error'), ('will_create', 'Will create'), ('will_update', 'Will update'), ('committed', 'Committed')], default='valid', max_length=12)),
                ('match_key', models.CharField(blank=True, max_length=200)),
                ('matched_object_id', models.CharField(blank=True, max_length=64)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['shop', 'import_type'], name='imports_imp_shop_id_8c19f3_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status'], name='imports_imp_job_id_b18fb2_idx'),
        ),
    ]
